---

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.09.01
  driver:
    name: ec2
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/rhel/6"
- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/ubuntu/trusty"
  run_list:
  - recipe[apt]
- name: ubuntu-12-04-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/ubuntu/precise"
  run_list:
  - recipe[apt]
- name: debian-7-0-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/debian/7"
  run_list:
  - recipe[apt]
- name: centos-7-0-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/rhel/7"
  run_list:
  - recipe[yum-epel]
- name: centos-6-5-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/rhel/6"
- name: centos-5-8-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/rhel/5"
- name: fedora-19-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.5/fedora/19"
  provisioner:
    root_path: /home/vagrant/kitchen

suites:
- name: default
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        local:
          filename: ""
        version:
          major: "2"
          minor: "0"
          incremental: "5"
- name: search
  run_list:
  - recipe[riak]
  attributes:
    riak:
      manage_java: true
      package:
        version:
          major: "2"
          minor: "0"
          incremental: "5"
      config:
        search.top_level: "on"
  excludes: ["freebsd-10.1", "freebsd-9.2"]
- name: enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: "2"
          minor: "0"
          incremental: "5"
        local:
          url: ""
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
- name: custom_package
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "custom_package"
- name: source
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: "2"
        minor: "0"
        incremental: "5"
