---

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.09.01
  driver:
    name: ec2
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.1-1.el6.x86_64.rpm"
          checksum: "59aadeab2dc00fba6d6d45575e7d678fc15411d39f195cfe6aec3be303acc071"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.1/rhel/6"
        enterprise:
          checksum: "???"
- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]
- name: ubuntu-12-04-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]
- name: debian-7-0-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[apt]
- name: centos-7-0-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
- name: centos-6-5-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
- name: centos-5-8-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
- name: fedora-19-x64
  driver:
    name: digitalocean
suites:
- name: default
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: "2"
          minor: "0"
          incremental: "1"
  excludes:
  - fedora-19-x64
- name: enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        url: "http://private.downloads.basho.com/riak_ee"
        version:
          major: "2"
          minor: "0"
          incremental: "1"
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
  excludes:
  - fedora-19-x64
- name: source
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: "2"
        minor: "0"
        incremental: "1"
