---

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.09.01
  driver:
    name: ec2
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.2-1.el6.x86_64.rpm"
          checksum: "ab51c3d65dcd63c1f8d94bdd241b26671b18fcb19d272f4397d07021cfa71a3c"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/rhel/6"
        enterprise:
          checksum: "???"
- name: ubuntu-14-04-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.2-1_amd64.deb"
          checksum: "cab9b89cd0ee82528669facee149c9d6f2a0d0e6fa89496406133ca9c28cd48e"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/ubuntu/trusty"
        enterprise:
          checksum: "???"
  run_list:
  - recipe[apt]
- name: ubuntu-12-04-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.2-1_amd64.deb"
          checksum: "db290d17208861b2eb8694d2eb3d1dc8e7ad280edf577fac8bd355446ca6b85a"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/ubuntu/precise"
        enterprise:
          checksum: "???"
  run_list:
  - recipe[apt]
- name: debian-7-0-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          filename: "riak_2.0.2-1_amd64.deb"
          checksum: "31ca5d472e992e3af267b440945239b110354a64fc197d2a3d73b93fc66483d4"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/debian/7"
        enterprise:
          checksum: "???"
  run_list:
  - recipe[apt]
- name: centos-7-0-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.2-1.el7.centos.x86_64.rpm"
          checksum: "15a732f0b79c934f8dbc3d5b86124a0eedfe7da6e1df84a595df15b2b703106d"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/rhel/7"
        enterprise:
          checksum: "???"
  run_list:
  - recipe[yum-epel]
- name: centos-6-5-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.2-1.el6.x86_64.rpm"
          checksum: "ab51c3d65dcd63c1f8d94bdd241b26671b18fcb19d272f4397d07021cfa71a3c"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/rhel/6"
        enterprise:
          checksum: "???"
- name: centos-5-8-x64
  driver:
    name: digitalocean
  run_list:
  - recipe[yum-epel]
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.2-1.el5.x86_64.rpm"
          checksum: "8b829b6b7349ace62d7a69ccb113ea5d52f5f39f4f39b08c900e5ffed1119cf5"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/rhel/5"
        enterprise:
          checksum: "???"
- name: fedora-19-x64
  driver:
    name: digitalocean
  attributes:
    riak:
      package:
        local:
          filename: "riak-2.0.2-1.fc19.x86_64.rpm"
          checksum: "7f182beaa3c79ac023811d23ef3957a07fabebd128b62fcc77ac710b98c72b98"
          url: "http://s3.amazonaws.com/downloads.basho.com/riak/2.0/2.0.2/fedora/19"
        enterprise:
          checksum: "???"
  provisioner:
    root_path: /home/vagrant/kitchen

suites:
- name: default
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        local:
          filename: ""
        version:
          major: "2"
          minor: "0"
          incremental: "2"
  excludes:
  - fedora-19-x64
- name: enterprise
  run_list:
  - recipe[riak]
  attributes:
    riak:
      package:
        url: "http://private.downloads.basho.com/riak_ee"
        version:
          major: "2"
          minor: "0"
          incremental: "2"
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
  excludes:
  - fedora-19-x64
- name: custom_package
  run_list:
  - recipe[riak]
  attributes: {}
  excludes:
   - fedora-19-x64
- name: source
  run_list:
  - recipe[riak]
  attributes:
    riak:
      install_method: "source"
      source:
        major: "2"
        minor: "0"
        incremental: "2"
